name: Run Scraper

on:
  schedule:
    - cron: '0 14 * * *'  # Runs daily at 21:00 Thailand time (UTC+7)
  workflow_dispatch:  # ✅ Allows manual trigger

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        run: uv python install

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        continue-on-error: true
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Dependencies
        run: |
          uv sync
          uv run playwright install

      - name: Load Environment Variables
        run: |
          echo "DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }}" >> $GITHUB_ENV
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
          echo "USERNAME=${{ secrets.USERNAME }}" >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV

      - name: Run Scraper
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: uv run python main.py 

      - name: Upload trace for debugging
        if: always()  # Run even if scraper fails
        uses: actions/upload-artifact@v4
        with:
          name: playwright-trace
          path: trace.zip

